### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'login' of undefined

### ISSUE THREAD

**Issue by kegri** [BearTS/Pterodactyl-v1-DiscordBot#4]
I registered the bot succesfull but when I run other commands, it gives this error that I don't know

`(node:15) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'login' of undefined
    at /home/container/commands/control/servers.js:64:24
(node:15) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by BearTS** [comment]
strange, may i know what hosting are you trying to use?

**Comment by kegri** [comment]
I'm using it on my brand new pterodactyl panel

**Comment by BearTS** [comment]
Hey About your issue @kegri 
The repository was archived for a while and now since I unarchived it because of requests from multiple users, 
I will rewrite this after my final exams which are ending in January

**Comment by BearTS** [comment]
@kegri The repository is updated to support latest version of Pterodactyl Panel
Edit: Therefore I am closing this issue
